version: '3.7'
services:
  # Oats Database
  oats_psql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
    ports:
      - '11543:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # Oats server
  oats_backend_server:
    build: .
    volumes:
      - ./:/oats/server
    ports:
      - '8080:3000'
    env_file:
      - .env
    depends_on:
      - oats_psql
    command: ['npm', 'run', 'dev']

volumes:
  database-data: {}