version: '3.7'
services:
  # Oats Database
  oats_psql:
    container_name: oats_psql
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
      POSTGRES_DB: ${POSTGRES_DB?}
      PGPORT: ${POSTGRES_PORT?}
    ports:
      - '${POSTGRES_PORT?}:${POSTGRES_PORT?}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # Oats server
  oats_backend_server:
    container_name: oats_backend_server
    build: .
    volumes:
      - ./:/oats/server
    ports:
      - '8080:3000'
    env_file:
      - .env
    depends_on:
      - oats_psql
    command: ['npm', 'run', 'dev']

volumes:
  database-data: {}